schema = "allodium.github.issue-mappings/v0"

[issues.issue-0001]
number = 1
url = "https://github.com/sguzman/allodium/issues/1"

[issues.issue-0002]
number = 2
url = "https://github.com/sguzman/allodium/issues/2"

[issues.issue-0003]
number = 3
url = "https://github.com/sguzman/allodium/issues/3"

[issues.issue-0004]
number = 5
url = "https://github.com/sguzman/allodium/issues/5"

[issues.issue-0005]
number = 6
url = "https://github.com/sguzman/allodium/issues/6"

[issues.issue-0006]
number = 8
url = "https://github.com/sguzman/allodium/issues/8"

[issues.issue-0007]
number = 17
url = "https://github.com/sguzman/allodium/issues/17"

[issues.issue-0008]
number = 18
url = "https://github.com/sguzman/allodium/issues/18"
